server:
  port: 8082
spring:
  devtools:
      restart:
        enabled: true
  datasource:
        url: jdbc:mysql://localhost:3306/jeesite4?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  http:
      encoding:
        force: true
  boot:
    admin:
      client:
        prefer-ip: true
      url: http://localhost:80821

mybatis:
    type-aliases-package: com.capinfo.entity
    mapper-locations: classpath*:mappers/*.xml
    check-config-location: true

mapper:
    mappers:
        - com.capinfo.mappers.MyBaseMapper
#        - tk.mybatis.mappers.common.Mapper
    not-empty: true
    identity: mysql

jackson:
  default-property-inclusion: non_null

# PageHelperConfig 可以替代此方案
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

capsp:
  uploadPath: ./file/
  isDayType: false

  imagePath: ./image/

logging:
  file: ./logs/capsp-log.log
  level:
    com.capinfo.mapper: debug

dataType: mysql